int maior(int num1, int num2);
int compara_matriz(Game matriz1, Game matriz2);
int find_pos(Game game, int numero, int *i, int *j);
int arround(Game game, int *top, int *right, int *down, int *left);
int get_g(Game *game);
void set_g(Game *game, int g);
int get_h(Game *game);
void set_char_size(Game *game, int size);
int get_char_size(Game *game);
void set_char(Game *game, char c);
char get_char(Game *game, int pos);
void print_matrix(Game game);
void print_pais(Game origem, Game destino);
